before_install:
- sudo apt-get update
- sudo apt-get install -y texlive-latex-extra texlive-lang-german texlive-math-extra
before_script:
- dir
- pwd
- cd ..
- dir
- f = File.new('Idiotenseite.tex', 'w')
- f.write('% !TEX root = Idiotenseite.tex')
- f.write("/n")
- f.write('\documentclass[10pt,oneside,a4paper,fleqn]{scrartcl}')
- f.write("/n")
- f.write('\usepackage[left=1cm,right=1cm,top=0.5cm,bottom=0.5cm,includeheadfoot]{geometry}')
- f.write("/n")
- f.write('\usepackage[utf8]{inputenc}')
- f.write("/n")
- f.write('\usepackage{multicol}')
- f.write("/n")
- f.write('\usepackage[english, ngerman]{babel}')
- f.write("/n")
- f.write('\usepackage[automark]{scrpage2}')
- f.write("/n")
- f.write('\usepackage{tabularx}')
- f.write("/n")
- f.write('\usepackage{amssymb}')
- f.write("/n")
- f.write('\usepackage{mathtools}')
- f.write("/n")
- f.write('\usepackage{bm}')
- f.write("/n")
- f.write('\usepackage{rotating}')
- f.write("/n")
- f.write('\usepackage[europeanresistors,americaninductors]{circuitikz}')
- f.write("/n")
- f.write('\newcommand{\buch}[1]{\texorpdfstring{$_{\textcolor{HSRLakeGreen}{\mbox{\small{#1}}}}$}{}}')
- f.write("/n")
- f.write('\newcommand{\buchSeite}[1]{\texorpdfstring{\ensuremath{_{\textcolor{red}{\mbox{\small{ S#1}}}}}}{}}')
- f.write("/n")
- f.write('\newcommand{\skript}[1]{\texorpdfstring{$_{\textcolor{HSRReed}{\mbox{\small{#1}}}}$}{}}')
- f.write("/n")
- f.write('\newcommand{\formelbuch}[1]{$_{\textcolor{red}{\mbox{\small{S#1}}}}$}')
- f.write("/n")
- f.write('\newcommand{\arraystretchOriginal}{1.5}')
- f.write("/n")
- f.write('\renewcommand{\arraystretch}{\arraystretchOriginal}')
- f.write("/n")
- f.write('\setlength{\parindent}{0pt}')
- f.write("/n")
- f.write('\begin{document}')
- f.write("/n")
- f.write('\input{idiotenseite/IdiotenseiteInclude}')
- f.write("/n")
- f.write('\end{document}')
- f.write("/n")
- f.close

- dir
- pwd
script:
- pdflatex -interaction=nonstopmode ./Idiotenseite.tex
- pdflatex -interaction=nonstopmode ./Idiotenseite.tex
deploy:
  provider: releases
  api_key: $GITHUB_RELEASE_TOKEN
  file:
   - ./Idiotenseite.pdf
  skip_cleanup: true
  on:
    tags: true
